name: languagetool
on: [pull_request]

jobs:
    languagetool:
        name: languagetool
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: reviewdog/action-languagetool@v1
                with:
                    github_token: ${{ secrets.TOKEN }}
                    reporter: github-pr-review
                    level: info